#!/bin/bash

# get things up to date

source .venv/bin/activate
uv self version 
uv self update 
uv sync 
cat pyproject.toml 
uv lock --verbose --upgrade 
uv sync --all-extras --dev 
uv --verbose pip install zensical
zensical --version

