#!/bin/bash

set -eo pipefail

# get repolist for a github org or owner
if [[ $# -lt 1 ]]; then
  echo "Usage:"
  cat $0
  exit
fi

repoowner=$1
frepoowner=$(echo "${repoowner}" \
             | inline-detox -s lower)

# fields NAME DESCRIPTION INFO UPDATED  

# this format is not predictable ...?!
gh repo list \
	"${repoowner}" \
	--limit 999 \
| tee "repos.${frepoowner}"

# change the format to csv
cut -c1-43,44-150,151-169,170-189 \
    --output-delimiter=\; \
    "repos.${frepoowner}" \
| sed 's/ *; */;/g' \
| tee "repos.${repoowner}.csv"

# $ gh repo list fg  --json 2>&1 | xargs 
# Specify one or more comma-separated fields for `--json`: assignableUsers codeOfConduct contactLinks createdAt defaultBranchRef deleteBranchOnMerge description diskUsage forkCount fundingLinks hasDiscussionsEnabled hasIssuesEnabled hasProjectsEnabled hasWikiEnabled homepageUrl id isArchived isBlankIssuesEnabled isEmpty isFork isInOrganization isMirror isPrivate isSecurityPolicyEnabled isTemplate isUserConfigurationRepository issueTemplates issues labels languages latestRelease licenseInfo mentionableUsers mergeCommitAllowed milestones mirrorUrl name nameWithOwner openGraphImageUrl owner parent primaryLanguage projects pullRequestTemplates pullRequests pushedAt rebaseMergeAllowed repositoryTopics securityPolicyUrl squashMergeAllowed sshUrl stargazerCount templateRepository updatedAt url usesCustomOpenGraphImage viewerCanAdminister viewerDefaultCommitEmail viewerDefaultMergeMethod viewerHasStarred viewerPermission viewerPossibleCommitEmails viewerSubscription visibility watchers

gh repo list \
  "${repoowner}" \
  --json url,name,createdAt,updatedAt,description,homepageUrl,isSecurityPolicyEnabled 

# TODO process the output of this
#
#   {
#    "createdAt": "2025-06-11T14:23:48Z",
#    "description": "An introduction to the architecture and design of the Git content manager",
#    "homepageUrl": "https://jwiegley.github.io/git-from-the-bottom-up/",
#    "isSecurityPolicyEnabled": false,
#    "name": "git-from-the-bottom-up",
#    "updatedAt": "2025-06-11T14:23:48Z",
#    "url": "https://github.com/Oa8choo2/git-from-the-bottom-up"
#  },

